name: data-science-at-scale
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>2.0.0
  - dask=2.25.0
  - dask-labextension>=2.0.0
  - jupyterlab
  - nodejs
  - dask-ml
  - numpy
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - requests
  - pytables
  - s3fs
